	; Unit Name
	Unit_None				equ 0
	Unit_Infantry			equ 1
	Unit_Mech				equ 2
	Unit_Medium_Tank		equ 3
	Unit_Megatank			equ 4
	Unit_Tank				equ 5
	Unit_Recon				equ 6
	Unit_APC				equ 7
	Unit_Neotank			equ 8
	Unit_Piperunner			equ 9
	Unit_Artillery			equ 10
	Unit_Rocket				equ 11
	Unit_Stealth			equ 12
	Unit_Black_Bomb			equ 13
	Unit_Anti_Air			equ 14
	Unit_Missile			equ 15
	Unit_Fighter			equ 16
	Unit_Bomber				equ 17
	Unit_Black_Boat			equ 18
	Unit_B_Copter			equ 19
	Unit_T_Copter			equ 20
	Unit_Battleship			equ 21
	Unit_Cruiser			equ 22
	Unit_Lander				equ 23
	Unit_Sub				equ 24
	Unit_Carrier			equ 25
	Unit_Oozium				equ 26
	
	; Unit Type
	Unit_Foot				equ 0
	Unit_Direct_Vehicle		equ 1
	Unit_Indirect_Vehicle	equ 2
	Unit_Plane				equ 3
	Unit_Copter				equ 4
	Unit_Navy				equ 5
	Unit_All				equ 6
	Unit_Direct_Combat		equ 7
	Unit_Indirect_Combat	equ 8
	Unit_Transport			equ 9
	Unit_Explode			equ 10